project:
  type: website

website:
  title: '<img src="TMS_logo_white.png" width="66" height="95">'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - news.qmd
      - events.qmd
      - people.qmd
      - resources.qmd
      - summer_school.qmd
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

